// <auto-generated />
using System;
using System.Collections.Generic;
using BoothDotDev.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BoothDotDev.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260809163220_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "book_state", new[] { "read", "reading", "plan_to_read" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "font_style", new[] { "sans_serif", "serif" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "project_status", new[] { "ongoing", "hiatus", "past", "retired" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "project_type", new[] { "app", "game", "library", "tool", "website" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "visibility", new[] { "none", "private", "unlisted", "published" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BoothDotDev.Data.Models.BlogPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("DisqusDomain")
                        .HasColumnType("text")
                        .HasColumnName("disqus_domain");

                    b.Property<string>("DisqusIdentifier")
                        .HasColumnType("text")
                        .HasColumnName("disqus_identifier");

                    b.Property<string>("DisqusPath")
                        .HasColumnType("text")
                        .HasColumnName("disqus_path");

                    b.Property<bool>("EnableComments")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_comments");

                    b.Property<string>("Excerpt")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("excerpt");

                    b.Property<bool>("IsRedirect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_redirect");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<DateTimeOffset>("Published")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published");

                    b.Property<string>("RedirectUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("redirect_url");

                    b.Property<bool>("ShowTableOfContents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("show_toc");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<bool>("TableOfContentsExpanded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("toc_open");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated");

                    b.Property<Visibility>("Visibility")
                        .HasColumnType("public.visibility")
                        .HasColumnName("visibility");

                    b.Property<int?>("WordPressId")
                        .HasColumnType("integer")
                        .HasColumnName("wordpress_id");

                    b.HasKey("Id")
                        .HasName("pk_blog_post");

                    b.ToTable("blog_post", "public");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.BlogPostCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<FontStyle>("FontStyle")
                        .HasColumnType("public.font_style")
                        .HasColumnName("font_style");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_category_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_blog_post_category");

                    b.HasIndex("ParentCategoryId")
                        .HasDatabaseName("ix_blog_post_category_parent_category_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_blog_post_category_slug");

                    b.ToTable("blog_post_category", "public");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.Book", b =>
                {
                    b.Property<string>("Isbn")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("isbn");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("author");

                    b.Property<BookState>("State")
                        .HasColumnType("public.book_state")
                        .HasColumnName("state");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("title");

                    b.HasKey("Isbn")
                        .HasName("pk_book");

                    b.ToTable("book", "public");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.CodeSnippet", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Language")
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.HasKey("Id", "Language")
                        .HasName("pk_code_snippet");

                    b.ToTable("code_snippet", "public");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.DevChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("OldId")
                        .HasColumnType("integer")
                        .HasColumnName("old_id");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<bool>("ShowSolution")
                        .HasColumnType("boolean")
                        .HasColumnName("show_solution");

                    b.Property<string>("Solution")
                        .HasColumnType("text")
                        .HasColumnName("solution");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Visibility>("Visibility")
                        .HasColumnType("public.visibility")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_dev_challenge");

                    b.ToTable("dev_challenge", "public");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.LegacyComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("author");

                    b.Property<string>("Avatar")
                        .HasMaxLength(32767)
                        .HasColumnType("character varying(32767)")
                        .HasColumnName("avatar");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(32767)
                        .HasColumnType("character varying(32767)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ParentComment")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_comment");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.HasKey("Id")
                        .HasName("pk_legacy_comment");

                    b.ToTable("legacy_comment", "public");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<string>("HeroUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hero_url");

                    b.PrimitiveCollection<List<string>>("Languages")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("languages");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<string>("RemoteTarget")
                        .HasColumnType("text")
                        .HasColumnName("remote_target");

                    b.Property<string>("RemoteUrl")
                        .HasColumnType("text")
                        .HasColumnName("remote_url");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<ProjectStatus>("Status")
                        .HasColumnType("public.project_status")
                        .HasColumnName("status");

                    b.Property<string>("Tagline")
                        .HasColumnType("text")
                        .HasColumnName("tagline");

                    b.Property<ProjectType>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("public.project_type")
                        .HasDefaultValue(ProjectType.App)
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_project");

                    b.ToTable("project", "public");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.SiteConfiguration", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_site_config");

                    b.ToTable("site_config", "public");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.Template", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Variant")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("variant");

                    b.Property<string>("FormatString")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("format_string");

                    b.HasKey("Name", "Variant")
                        .HasName("pk_template");

                    b.ToTable("template", "public");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.TutorialArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<bool>("EnableComments")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_comments");

                    b.Property<string>("Excerpt")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("excerpt");

                    b.Property<Guid>("Folder")
                        .HasColumnType("uuid")
                        .HasColumnName("folder");

                    b.Property<Guid?>("NextPart")
                        .HasColumnType("uuid")
                        .HasColumnName("next_part");

                    b.Property<string>("PreviewImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("preview_image_url");

                    b.Property<Guid?>("PreviousPart")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_part");

                    b.Property<DateTimeOffset>("Published")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<Guid?>("RedirectFrom")
                        .HasColumnType("uuid")
                        .HasColumnName("redirect_from");

                    b.Property<bool>("ShowTableOfContents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("show_toc");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<bool>("TableOfContentsExpanded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("toc_open");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated");

                    b.Property<Visibility>("Visibility")
                        .HasColumnType("public.visibility")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_tutorial_article");

                    b.ToTable("tutorial_article", "public");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.TutorialFolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<Guid?>("Parent")
                        .HasColumnType("uuid")
                        .HasColumnName("parent");

                    b.Property<string>("PreviewImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("preview_image_url");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<Visibility>("Visibility")
                        .HasColumnType("public.visibility")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_tutorial_folder");

                    b.ToTable("tutorial_folder", "public");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("display_name");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email_address");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<DateTimeOffset>("Registered")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("salt");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.ToTable("user", "public");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.BlogPostCategory", b =>
                {
                    b.HasOne("BoothDotDev.Data.Models.BlogPostCategory", "ParentCategory")
                        .WithMany("Children")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_blog_post_category_blog_post_category_parent_category_id");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.BlogPostCategory", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
