// <auto-generated />
using System;
using System.Collections.Generic;
using BoothDotDev.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BoothDotDev.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260822002151_DropDevChallengePassword")]
    partial class DropDevChallengePassword
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "book_state", new[] { "read", "reading", "plan_to_read" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "font_style", new[] { "sans_serif", "serif" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "project_status", new[] { "ongoing", "hiatus", "past", "retired" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "project_type", new[] { "app", "game", "library", "tool", "website" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "visibility", new[] { "none", "private", "unlisted", "published" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BoothDotDev.Data.Models.ArtworkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("description");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<bool>("IsWorkInProgress")
                        .HasColumnType("boolean")
                        .HasColumnName("is_work_in_progress");

                    b.Property<string>("MadeWith")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("made_with");

                    b.Property<DateTimeOffset>("Published")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resolution");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<Visibility>("Visibility")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("public.visibility")
                        .HasDefaultValue(Visibility.Published)
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_artwork_item");

                    b.ToTable("artwork_item", "public");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.BlogPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<Guid?>("CurrentDraftId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_draft_id");

                    b.Property<bool>("EnableComments")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_comments");

                    b.Property<bool>("IsRedirect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_redirect");

                    b.Property<DateTimeOffset>("Published")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published");

                    b.Property<string>("RedirectUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("redirect_url");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset?>("TrashedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trashed_at");

                    b.Property<DateTimeOffset?>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated");

                    b.Property<int?>("WordPressId")
                        .HasColumnType("integer")
                        .HasColumnName("wordpress_id");

                    b.HasKey("Id")
                        .HasName("pk_blog_post");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_blog_post_author_id");

                    b.HasIndex("CurrentDraftId")
                        .HasDatabaseName("ix_blog_post_current_draft_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_blog_post_slug");

                    b.HasIndex("TrashedAt")
                        .HasDatabaseName("ix_blog_post_trashed_at");

                    b.ToTable("blog_post", "public");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.BlogPostCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<FontStyle>("FontStyle")
                        .HasColumnType("public.font_style")
                        .HasColumnName("font_style");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_category_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_blog_post_category");

                    b.HasIndex("ParentCategoryId")
                        .HasDatabaseName("ix_blog_post_category_parent_category_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_blog_post_category_slug");

                    b.ToTable("blog_post_category", "public");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.BlogPostDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BlogPostId")
                        .HasColumnType("uuid")
                        .HasColumnName("blog_post_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Excerpt")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("excerpt");

                    b.Property<bool>("ShowTableOfContents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("show_toc");

                    b.Property<bool>("TableOfContentsExpanded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("toc_open");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<Visibility>("Visibility")
                        .HasColumnType("public.visibility")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_blog_post_draft");

                    b.HasIndex("BlogPostId")
                        .HasDatabaseName("ix_blog_post_draft_blog_post_id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_blog_post_draft_category_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_blog_post_draft_created_at");

                    b.ToTable("blog_post_draft", "public");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.Book", b =>
                {
                    b.Property<string>("Isbn")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("isbn");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("author");

                    b.Property<BookState>("State")
                        .HasColumnType("public.book_state")
                        .HasColumnName("state");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("title");

                    b.HasKey("Isbn")
                        .HasName("pk_book");

                    b.ToTable("book", "public");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.CodeSnippet", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Language")
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.HasKey("Id", "Language")
                        .HasName("pk_code_snippet");

                    b.ToTable("code_snippet", "public");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.DevChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CurrentDraftId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_draft_id");

                    b.Property<int?>("OldId")
                        .HasColumnType("integer")
                        .HasColumnName("old_id");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<DateTimeOffset?>("TrashedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trashed_at");

                    b.Property<DateTimeOffset?>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated");

                    b.HasKey("Id")
                        .HasName("pk_dev_challenge");

                    b.HasIndex("CurrentDraftId")
                        .HasDatabaseName("ix_dev_challenge_current_draft_id");

                    b.HasIndex("TrashedAt")
                        .HasDatabaseName("ix_dev_challenge_trashed_at");

                    b.ToTable("dev_challenge", "public");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.DevChallengeDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("DevChallengeId")
                        .HasColumnType("uuid")
                        .HasColumnName("dev_challenge_id");

                    b.Property<bool>("ShowSolution")
                        .HasColumnType("boolean")
                        .HasColumnName("show_solution");

                    b.Property<string>("Solution")
                        .HasColumnType("text")
                        .HasColumnName("solution");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Visibility>("Visibility")
                        .HasColumnType("public.visibility")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_dev_challenge_draft");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_dev_challenge_draft_created_at");

                    b.HasIndex("DevChallengeId")
                        .HasDatabaseName("ix_dev_challenge_draft_dev_challenge_id");

                    b.ToTable("dev_challenge_draft", "public");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.LegacyComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("author");

                    b.Property<string>("Avatar")
                        .HasMaxLength(32767)
                        .HasColumnType("character varying(32767)")
                        .HasColumnName("avatar");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(32767)
                        .HasColumnType("character varying(32767)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ParentComment")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_comment");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.HasKey("Id")
                        .HasName("pk_legacy_comment");

                    b.ToTable("legacy_comment", "public");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.MusicItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("description");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<bool>("IsWorkInProgress")
                        .HasColumnType("boolean")
                        .HasColumnName("is_work_in_progress");

                    b.Property<string>("MadeWith")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("made_with");

                    b.Property<DateTimeOffset>("Published")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<Visibility>("Visibility")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("public.visibility")
                        .HasDefaultValue(Visibility.Published)
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_music_item");

                    b.ToTable("music_item", "public");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CurrentDraftId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_draft_id");

                    b.Property<DateTimeOffset>("Published")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published");

                    b.Property<DateTimeOffset?>("TrashedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trashed_at");

                    b.Property<DateTimeOffset?>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated");

                    b.HasKey("Id")
                        .HasName("pk_note");

                    b.HasIndex("CurrentDraftId")
                        .HasDatabaseName("ix_note_current_draft_id");

                    b.HasIndex("TrashedAt")
                        .HasDatabaseName("ix_note_trashed_at");

                    b.ToTable("note", "public");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.NoteDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<FontStyle>("FontStyle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("public.font_style")
                        .HasDefaultValue(FontStyle.Serif)
                        .HasColumnName("font_style");

                    b.Property<Guid>("NoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("note_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<Visibility>("Visibility")
                        .HasColumnType("public.visibility")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_note_draft");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_note_draft_created_at");

                    b.HasIndex("NoteId")
                        .HasDatabaseName("ix_note_draft_note_id");

                    b.ToTable("note_draft", "public");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<string>("HeroUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hero_url");

                    b.PrimitiveCollection<List<string>>("Languages")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("languages");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<string>("RemoteTarget")
                        .HasColumnType("text")
                        .HasColumnName("remote_target");

                    b.Property<string>("RemoteUrl")
                        .HasColumnType("text")
                        .HasColumnName("remote_url");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<ProjectStatus>("Status")
                        .HasColumnType("public.project_status")
                        .HasColumnName("status");

                    b.Property<string>("Tagline")
                        .HasColumnType("text")
                        .HasColumnName("tagline");

                    b.Property<ProjectType>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("public.project_type")
                        .HasDefaultValue(ProjectType.App)
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_project");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_project_slug");

                    b.ToTable("project", "public");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.ProjectDevlog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<bool>("EnableComments")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_comments");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset>("Published")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated");

                    b.Property<Visibility>("Visibility")
                        .HasColumnType("public.visibility")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_devlog");

                    b.ToTable("devlog", "public");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.SiteConfiguration", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_site_config");

                    b.ToTable("site_config", "public");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.TutorialArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<bool>("EnableComments")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_comments");

                    b.Property<string>("Excerpt")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("excerpt");

                    b.Property<Guid>("Folder")
                        .HasColumnType("uuid")
                        .HasColumnName("folder");

                    b.Property<Guid?>("NextPart")
                        .HasColumnType("uuid")
                        .HasColumnName("next_part");

                    b.Property<string>("PreviewImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("preview_image_url");

                    b.Property<Guid?>("PreviousPart")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_part");

                    b.Property<DateTimeOffset>("Published")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<Guid?>("RedirectFrom")
                        .HasColumnType("uuid")
                        .HasColumnName("redirect_from");

                    b.Property<bool>("ShowTableOfContents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("show_toc");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<bool>("TableOfContentsExpanded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("toc_open");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated");

                    b.Property<Visibility>("Visibility")
                        .HasColumnType("public.visibility")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_tutorial_article");

                    b.HasIndex("Folder")
                        .HasDatabaseName("ix_tutorial_article_folder");

                    b.ToTable("tutorial_article", "public");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.TutorialFolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<Guid?>("Parent")
                        .HasColumnType("uuid")
                        .HasColumnName("parent");

                    b.Property<string>("PreviewImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("preview_image_url");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<Visibility>("Visibility")
                        .HasColumnType("public.visibility")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_tutorial_folder");

                    b.HasIndex("Parent")
                        .HasDatabaseName("ix_tutorial_folder_parent");

                    b.ToTable("tutorial_folder", "public");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("display_name");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email_address");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<DateTimeOffset>("Registered")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("salt");

                    b.Property<string>("TotpSecret")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("totp_secret");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.ToTable("user", "public");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.BlogPost", b =>
                {
                    b.HasOne("BoothDotDev.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_blog_post_users_author_id");

                    b.HasOne("BoothDotDev.Data.Models.BlogPostDraft", "CurrentDraft")
                        .WithMany()
                        .HasForeignKey("CurrentDraftId")
                        .HasConstraintName("fk_blog_post_blog_post_drafts_current_draft_id");

                    b.Navigation("CurrentDraft");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.BlogPostCategory", b =>
                {
                    b.HasOne("BoothDotDev.Data.Models.BlogPostCategory", "ParentCategory")
                        .WithMany("Children")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_blog_post_category_blog_post_category_parent_category_id");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.BlogPostDraft", b =>
                {
                    b.HasOne("BoothDotDev.Data.Models.BlogPost", null)
                        .WithMany()
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_blog_post_draft_blog_post_blog_post_id");

                    b.HasOne("BoothDotDev.Data.Models.BlogPostCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_blog_post_draft_blog_post_category_category_id");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.DevChallenge", b =>
                {
                    b.HasOne("BoothDotDev.Data.Models.DevChallengeDraft", "CurrentDraft")
                        .WithMany()
                        .HasForeignKey("CurrentDraftId")
                        .HasConstraintName("fk_dev_challenge_dev_challenge_drafts_current_draft_id");

                    b.Navigation("CurrentDraft");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.DevChallengeDraft", b =>
                {
                    b.HasOne("BoothDotDev.Data.Models.DevChallenge", null)
                        .WithMany()
                        .HasForeignKey("DevChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dev_challenge_draft_dev_challenge_dev_challenge_id");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.Note", b =>
                {
                    b.HasOne("BoothDotDev.Data.Models.NoteDraft", "CurrentDraft")
                        .WithMany()
                        .HasForeignKey("CurrentDraftId")
                        .HasConstraintName("fk_note_note_drafts_current_draft_id");

                    b.Navigation("CurrentDraft");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.NoteDraft", b =>
                {
                    b.HasOne("BoothDotDev.Data.Models.Note", null)
                        .WithMany()
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_note_draft_note_note_id");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.TutorialArticle", b =>
                {
                    b.HasOne("BoothDotDev.Data.Models.TutorialFolder", null)
                        .WithMany()
                        .HasForeignKey("Folder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tutorial_article_tutorial_folders_folder");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.TutorialFolder", b =>
                {
                    b.HasOne("BoothDotDev.Data.Models.TutorialFolder", null)
                        .WithMany()
                        .HasForeignKey("Parent")
                        .HasConstraintName("fk_tutorial_folder_tutorial_folder_parent");
                });

            modelBuilder.Entity("BoothDotDev.Data.Models.BlogPostCategory", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
