services:
  boothdotdev:
    container_name: booth.dev
    pull_policy: build
    build:
      context: .
      dockerfile: BoothDotDev/Dockerfile
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
    volumes:
      - /var/log/boothdotdev/site:/app/logs
      - /etc/boothdotdev/site:/app/data
      - ${CDN_PATH}:/app/cdn
    ports:
      - "2845:8080"
    restart: unless-stopped

  boothdotdev-db:
    container_name: booth.dev-db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_LOCATION}:/var/lib/postgresql
    restart: unless-stopped

networks:
  default:
    driver: bridge
