import {initTheme} from './theme.ts';
import {initCopyButtons} from './clipboard.ts';
import {initContentFeatures} from './content-rendering.ts';
import {initPostAuthoring} from './admin/post-authoring.ts';
import {initAltTextPopovers} from './images.ts';
import {initSearch} from './search.ts';
import {initConfirmForms} from './confirm.ts';
import {initBulkSelect} from './bulk-select.ts';
import {initContentPreview} from './admin/content-preview.ts';
import {initMediaManager} from './admin/media-manager.ts';
import {initAvatarFallback} from './avatar-fallback.ts';
import {initUserAuthoring} from './admin/user-authoring.ts';
import {initPasskeyRegistration} from './admin/passkey-registration.ts';
import {initPasskeyLogin} from './admin/passkey-login.ts';
import {initCdnBrowser} from './admin/cdn-browser.ts';
import {initReorder} from './admin/reorder.ts';
import {initSomedayEditorPreview} from './admin/someday-editor.ts';
import {initStreakEditor} from './admin/streak-editor.ts';
import {initStreakCalendar} from './admin/streak-calendar.ts';
import {initBookLookup} from './admin/book-lookup.ts';
import {initEditionEditor} from './admin/edition-editor.ts';
import {initPlayableLookup} from './admin/playable-lookup.ts';
import {initWatchableLookup} from './admin/watchable-lookup.ts';
import {initSortTitle} from './admin/sort-title.ts';
import {initStateGroups} from './admin/state-groups.ts';
import {initNavDrawer} from './admin/nav-drawer.ts';

(() => {
    initTheme();
    initAltTextPopovers();
    initCopyButtons();
    initContentFeatures();
    initPostAuthoring();
    initSearch();
    initConfirmForms();
    initBulkSelect();
    initContentPreview();
    initMediaManager();
    initAvatarFallback();
    initUserAuthoring();
    initPasskeyRegistration();
    initPasskeyLogin();
    initCdnBrowser();
    initReorder();
    initSomedayEditorPreview();
    initStreakEditor();
    initStreakCalendar();
    initBookLookup();
    initEditionEditor();
    initPlayableLookup();
    initWatchableLookup();
    initSortTitle();
    initStateGroups();
    initNavDrawer();
})();
