import {initCommandPalette} from './command-palette.ts';
import {initCopyButtons, initCryptoCopyButtons} from './clipboard.ts';
import {initContentFeatures} from './content-rendering.ts';
import {initEasterEggs} from './easter-eggs.ts';
import {initFiltering} from './filtering.ts';
import {initGiscusTheme} from './giscus-theme.ts';
import {initAltTextPopovers} from './images.ts';
import {initLightbox} from './lightbox.ts';
import {initAvatarFallback} from './avatar-fallback.ts';
import {initNowClock} from './now-clock.ts';
import {initRetryButtons} from './retry-button.ts';
import {initRuledPaper} from './ruled-paper.ts';
import {initHeaderAutoHide} from './header-auto-hide.ts';
import {initTheme} from './theme.ts';
import {initVoiceFontToggle} from './voice-font.ts';

(() => {
    initTheme();
    initVoiceFontToggle();
    initHeaderAutoHide();
    initAltTextPopovers();
    initCopyButtons();
    initCryptoCopyButtons();
    initContentFeatures();
    initEasterEggs();
    initFiltering();
    initGiscusTheme();
    initLightbox();
    initCommandPalette();
    initAvatarFallback();
    initNowClock();
    initRetryButtons();
    initRuledPaper();
})();
